name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.7.0"
  AWS_REGION:  "ap-south-1"
  ENVIRONMENT: "dev"

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/${{ env.ENVIRONMENT }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/environments/${{ env.ENVIRONMENT }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name eks-platform-dev

      - name: Verify cluster
        run: kubectl get nodes